export const CREATE_URL_REQUEST = "CREATE_URL_REQUEST";
export const CREATE_URL_SUCCESS = "CREATE_URL_SUCCESS";
export const CREATE_URL_FAIL = "CREATE_URL_FAIL";

export const MY_URLS_REQUEST = "MY_URLS_REQUEST";
export const MY_URLS_SUCCESS = "MY_URLS_SUCCESS";
export const MY_URLS_FAIL = "MY_URLS_FAIL";

export const DELETE_URL_REQUEST = "DELETE_URL_REQUEST";
export const DELETE_URL_SUCCESS = "DELETE_URL_SUCCESS";
export const DELETE_URL_FAIL = "DELETE_URL_FAIL";

export const EDIT_URL_REQUEST = "EDIT_URL_REQUEST";
export const EDIT_URL_SUCCESS = "EDIT_URL_SUCCESS";
export const EDIT_URL_FAIL = "EDIT_URL_FAIL";
export const EDIT_URL_RESET = "EDIT_URL_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";